### ISSUE TITLE
How about a possibility to set your WebUI's URL?

### ISSUE THREAD

**Issue by Ingvix** [jlledo/hs-batcher#1]
I have my qbittorrent running on a server machine with a custom port so the default address doesn't really cut it.

**Comment by jlledo** [comment]
Hi there! This feels like getting my first customer :D; I thought no one would ever use this!

This is a good idea, I'll learn how to create a config page in which to put this option. If all else fails, at the very least I'll add a textbox to the UI to cover this use case.

**Comment by Ingvix** [comment]
Also as a sidenote, inpecting the code, it seems that it just blindly posts the torrents to qbittorrent in the order they are on the site, which usually starts from the latest. I think it would be smarter to add them in a chronological order so the first episode would get the first priority. If there's a limit how many torrents are downloading at the same time, it would start with the first ones which you usually want to watch first too.

**Comment by jlledo** [comment]
I've just merged the features into master (#2), please let me know if that works for you.

You can temporarily install the extension by following the steps in this [link](https://extensionworkshop.com/documentation/develop/temporary-installation-in-firefox/). I'll release a signed version once everything is working fine.

**Comment by Ingvix** [comment]
It doesn't seem to work. I get the elements on the page but clicking download doesn't do anything. I have whitelisted my home network in qBittorrent so it shouldn't require any authentication. I set just the bare IP and port in the options. Developer console doesn't show anything related to the addon.

**Comment by jlledo** [comment]
Damn, I'll add some debugging code so we can triage a bit better. Have you verified you qBittorrent version? I'm also going to try to reproduce your setup on my end.

In the meantime, could you take a look at qBittorrent's logs and post any relevant information? You can find the log file location by going to Preferences > Behavior and scrolling all the way down.

<img width="891" alt="Screenshot 2020-03-22 at 15 37 33" src="https://user-images.githubusercontent.com/18508536/77252343-86ed3780-6c53-11ea-8ed3-ea2718109199.png">

If you have a packet sniffing tool, e.g. Wireshark, you can also check whether the "add torrent" request is being sent correctly or not.

**Comment by jlledo** [comment]
I think I've got it. The extension now needs expanded permissions in order to be able to make requests to remote hosts, instead of just "localhost".

Please take a look at #3, checkout  e4b0c1b15968a646f60fe825e2974d490bfa64d7, and let me know if that works for you. I'll merge the PR if all goes well.

**Comment by Ingvix** [comment]
You got it. Works like a charm now, thanks.

**Comment by jlledo** [comment]
I'm glad :D, thanks for opening my first ever issue!
